import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class Main {
    public static void main(String[] args) {
        String url = "jdbc:h2:file:./test";
        String username = "sa";
        String password = "password";
        try(Connection connection = DriverManager.getConnection(url, username, password)) {
            System.out.println("Is connection valid? " + connection.isValid(1000));
            try(Statement statement = connection.createStatement()) {
                String sql = "CREATE TABLE IF NOT EXISTS ACCOUNTS ( " +
                        "id INT GENERATED BY DEFAULT AS IDENTITY, " +
                        "name VARCHAR(50) );";
                statement.executeUpdate(sql);
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

    }
}
