import java.sql.*;

public class Main {
    public static void main(String[] args) {
        String url = "jdbc:h2:file:./test";
        String username = "sa";
        String password = "password";
        try(Connection connection = DriverManager.getConnection(url, username, password)) {
            System.out.println("Is connection valid? " + connection.isValid(1000));
            try(Statement statement = connection.createStatement()) {
                String sql = "CREATE TABLE IF NOT EXISTS ACCOUNTS ( " +
                        "id INT GENERATED BY DEFAULT AS IDENTITY, " +
                        "name VARCHAR(50) );";
                statement.executeUpdate(sql);

                String sqlInsert = "INSERT INTO ACCOUNTS (name) " +
                        "VALUES ('John')," +
                        " ('Max');";
                int rowsChanged = statement.executeUpdate(sqlInsert);
                System.out.println("There were " + rowsChanged + " rows inserted in ACCOUNTS table.");

                String sqlSelect = "SELECT id, name FROM ACCOUNTS;";
                try(ResultSet rs = statement.executeQuery(sqlSelect)) {
                    while(rs.next()){
                        int id = rs.getInt("id");
                        String name = rs.getString("name");
                        System.out.println("Account: " + "id = " + id + " name = " + name);
                    }

                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

    }
}
